namespace Delta.Trinity.Hotfixes
{
    public partial class ItemSparse
    {
        public int Id { get; set; }
        public long AllowableRace { get; set; }
        public string Display { get; set; }
        public string Display1 { get; set; }
        public string Display2 { get; set; }
        public string Display3 { get; set; }
        public string Description { get; set; }
        public int Flags1 { get; set; }
        public int Flags2 { get; set; }
        public int Flags3 { get; set; }
        public int Flags4 { get; set; }
        public float PriceRandomValue { get; set; }
        public float PriceVariance { get; set; }
        public int VendorStackCount { get; set; }
        public int BuyPrice { get; set; }
        public int SellPrice { get; set; }
        public int RequiredAbility { get; set; }
        public int MaxCount { get; set; }
        public int Stackable { get; set; }
        public int StatPercentEditor1 { get; set; }
        public int StatPercentEditor2 { get; set; }
        public int StatPercentEditor3 { get; set; }
        public int StatPercentEditor4 { get; set; }
        public int StatPercentEditor5 { get; set; }
        public int StatPercentEditor6 { get; set; }
        public int StatPercentEditor7 { get; set; }
        public int StatPercentEditor8 { get; set; }
        public int StatPercentEditor9 { get; set; }
        public int StatPercentEditor10 { get; set; }
        public float StatPercentageOfSocket1 { get; set; }
        public float StatPercentageOfSocket2 { get; set; }
        public float StatPercentageOfSocket3 { get; set; }
        public float StatPercentageOfSocket4 { get; set; }
        public float StatPercentageOfSocket5 { get; set; }
        public float StatPercentageOfSocket6 { get; set; }
        public float StatPercentageOfSocket7 { get; set; }
        public float StatPercentageOfSocket8 { get; set; }
        public float StatPercentageOfSocket9 { get; set; }
        public float StatPercentageOfSocket10 { get; set; }
        public float ItemRange { get; set; }
        public int BagFamily { get; set; }
        public float QualityModifier { get; set; }
        public int DurationInInventory { get; set; }
        public float DmgVariance { get; set; }
        public short AllowableClass { get; set; }
        public short ItemLevel { get; set; }
        public short RequiredSkill { get; set; }
        public short RequiredSkillRank { get; set; }
        public short MinFactionId { get; set; }
        public short ItemStatValue1 { get; set; }
        public short ItemStatValue2 { get; set; }
        public short ItemStatValue3 { get; set; }
        public short ItemStatValue4 { get; set; }
        public short ItemStatValue5 { get; set; }
        public short ItemStatValue6 { get; set; }
        public short ItemStatValue7 { get; set; }
        public short ItemStatValue8 { get; set; }
        public short ItemStatValue9 { get; set; }
        public short ItemStatValue10 { get; set; }
        public short ScalingStatDistributionId { get; set; }
        public short ItemDelay { get; set; }
        public short PageId { get; set; }
        public short StartQuestId { get; set; }
        public short LockId { get; set; }
        public short RandomSelect { get; set; }
        public short ItemRandomSuffixGroupId { get; set; }
        public short ItemSet { get; set; }
        public short ZoneBound { get; set; }
        public short InstanceBound { get; set; }
        public short TotemCategoryId { get; set; }
        public short SocketMatchEnchantmentId { get; set; }
        public short GemProperties { get; set; }
        public short LimitCategory { get; set; }
        public short RequiredHoliday { get; set; }
        public short RequiredTransmogHoliday { get; set; }
        public short ItemNameDescriptionId { get; set; }
        public byte OverallQualityId { get; set; }
        public byte InventoryType { get; set; }
        public byte RequiredLevel { get; set; }
        public byte RequiredPvprank { get; set; }
        public byte RequiredPvpmedal { get; set; }
        public byte MinReputation { get; set; }
        public byte ContainerSlots { get; set; }
        public byte StatModifierBonusStat1 { get; set; }
        public byte StatModifierBonusStat2 { get; set; }
        public byte StatModifierBonusStat3 { get; set; }
        public byte StatModifierBonusStat4 { get; set; }
        public byte StatModifierBonusStat5 { get; set; }
        public byte StatModifierBonusStat6 { get; set; }
        public byte StatModifierBonusStat7 { get; set; }
        public byte StatModifierBonusStat8 { get; set; }
        public byte StatModifierBonusStat9 { get; set; }
        public byte StatModifierBonusStat10 { get; set; }
        public byte DamageDamageType { get; set; }
        public byte Bonding { get; set; }
        public byte LanguageId { get; set; }
        public byte PageMaterialId { get; set; }
        public byte Material { get; set; }
        public byte SheatheType { get; set; }
        public byte SocketType1 { get; set; }
        public byte SocketType2 { get; set; }
        public byte SocketType3 { get; set; }
        public byte SpellWeightCategory { get; set; }
        public byte SpellWeight { get; set; }
        public byte ArtifactId { get; set; }
        public byte ExpansionId { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
