namespace Delta.Trinity.Hotfixes
{
    public partial class PlayerCondition
    {
        public long RaceMask { get; set; }
        public string FailureDescription { get; set; }
        public int Id { get; set; }
        public byte Flags { get; set; }
        public short MinLevel { get; set; }
        public short MaxLevel { get; set; }
        public int ClassMask { get; set; }
        public byte Gender { get; set; }
        public byte NativeGender { get; set; }
        public int SkillLogic { get; set; }
        public byte LanguageId { get; set; }
        public byte MinLanguage { get; set; }
        public int MaxLanguage { get; set; }
        public short MaxFactionId { get; set; }
        public byte MaxReputation { get; set; }
        public int ReputationLogic { get; set; }
        public byte CurrentPvpFaction { get; set; }
        public byte MinPvprank { get; set; }
        public byte MaxPvprank { get; set; }
        public byte PvpMedal { get; set; }
        public int PrevQuestLogic { get; set; }
        public int CurrQuestLogic { get; set; }
        public int CurrentCompletedQuestLogic { get; set; }
        public int SpellLogic { get; set; }
        public int ItemLogic { get; set; }
        public byte ItemFlags { get; set; }
        public int AuraSpellLogic { get; set; }
        public short WorldStateExpressionId { get; set; }
        public byte WeatherId { get; set; }
        public byte PartyStatus { get; set; }
        public byte LifetimeMaxPvprank { get; set; }
        public int AchievementLogic { get; set; }
        public int LfgLogic { get; set; }
        public int AreaLogic { get; set; }
        public int CurrencyLogic { get; set; }
        public short QuestKillId { get; set; }
        public int QuestKillLogic { get; set; }
        public byte MinExpansionLevel { get; set; }
        public byte MaxExpansionLevel { get; set; }
        public byte MinExpansionTier { get; set; }
        public byte MaxExpansionTier { get; set; }
        public byte MinGuildLevel { get; set; }
        public byte MaxGuildLevel { get; set; }
        public byte PhaseUseFlags { get; set; }
        public short PhaseId { get; set; }
        public int PhaseGroupId { get; set; }
        public int MinAvgItemLevel { get; set; }
        public int MaxAvgItemLevel { get; set; }
        public short MinAvgEquippedItemLevel { get; set; }
        public short MaxAvgEquippedItemLevel { get; set; }
        public byte ChrSpecializationIndex { get; set; }
        public byte ChrSpecializationRole { get; set; }
        public byte PowerType { get; set; }
        public byte PowerTypeComp { get; set; }
        public byte PowerTypeValue { get; set; }
        public int ModifierTreeId { get; set; }
        public int WeaponSubclassMask { get; set; }
        public short SkillId1 { get; set; }
        public short SkillId2 { get; set; }
        public short SkillId3 { get; set; }
        public short SkillId4 { get; set; }
        public short MinSkill1 { get; set; }
        public short MinSkill2 { get; set; }
        public short MinSkill3 { get; set; }
        public short MinSkill4 { get; set; }
        public short MaxSkill1 { get; set; }
        public short MaxSkill2 { get; set; }
        public short MaxSkill3 { get; set; }
        public short MaxSkill4 { get; set; }
        public int MinFactionId1 { get; set; }
        public int MinFactionId2 { get; set; }
        public int MinFactionId3 { get; set; }
        public byte MinReputation1 { get; set; }
        public byte MinReputation2 { get; set; }
        public byte MinReputation3 { get; set; }
        public short PrevQuestId1 { get; set; }
        public short PrevQuestId2 { get; set; }
        public short PrevQuestId3 { get; set; }
        public short PrevQuestId4 { get; set; }
        public short CurrQuestId1 { get; set; }
        public short CurrQuestId2 { get; set; }
        public short CurrQuestId3 { get; set; }
        public short CurrQuestId4 { get; set; }
        public short CurrentCompletedQuestId1 { get; set; }
        public short CurrentCompletedQuestId2 { get; set; }
        public short CurrentCompletedQuestId3 { get; set; }
        public short CurrentCompletedQuestId4 { get; set; }
        public int SpellId1 { get; set; }
        public int SpellId2 { get; set; }
        public int SpellId3 { get; set; }
        public int SpellId4 { get; set; }
        public int ItemId1 { get; set; }
        public int ItemId2 { get; set; }
        public int ItemId3 { get; set; }
        public int ItemId4 { get; set; }
        public int ItemCount1 { get; set; }
        public int ItemCount2 { get; set; }
        public int ItemCount3 { get; set; }
        public int ItemCount4 { get; set; }
        public short Explored1 { get; set; }
        public short Explored2 { get; set; }
        public int Time1 { get; set; }
        public int Time2 { get; set; }
        public int AuraSpellId1 { get; set; }
        public int AuraSpellId2 { get; set; }
        public int AuraSpellId3 { get; set; }
        public int AuraSpellId4 { get; set; }
        public byte AuraStacks1 { get; set; }
        public byte AuraStacks2 { get; set; }
        public byte AuraStacks3 { get; set; }
        public byte AuraStacks4 { get; set; }
        public short Achievement1 { get; set; }
        public short Achievement2 { get; set; }
        public short Achievement3 { get; set; }
        public short Achievement4 { get; set; }
        public byte LfgStatus1 { get; set; }
        public byte LfgStatus2 { get; set; }
        public byte LfgStatus3 { get; set; }
        public byte LfgStatus4 { get; set; }
        public byte LfgCompare1 { get; set; }
        public byte LfgCompare2 { get; set; }
        public byte LfgCompare3 { get; set; }
        public byte LfgCompare4 { get; set; }
        public int LfgValue1 { get; set; }
        public int LfgValue2 { get; set; }
        public int LfgValue3 { get; set; }
        public int LfgValue4 { get; set; }
        public short AreaId1 { get; set; }
        public short AreaId2 { get; set; }
        public short AreaId3 { get; set; }
        public short AreaId4 { get; set; }
        public int CurrencyId1 { get; set; }
        public int CurrencyId2 { get; set; }
        public int CurrencyId3 { get; set; }
        public int CurrencyId4 { get; set; }
        public int CurrencyCount1 { get; set; }
        public int CurrencyCount2 { get; set; }
        public int CurrencyCount3 { get; set; }
        public int CurrencyCount4 { get; set; }
        public int QuestKillMonster1 { get; set; }
        public int QuestKillMonster2 { get; set; }
        public int QuestKillMonster3 { get; set; }
        public int QuestKillMonster4 { get; set; }
        public int QuestKillMonster5 { get; set; }
        public int QuestKillMonster6 { get; set; }
        public int MovementFlags1 { get; set; }
        public int MovementFlags2 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
