namespace Delta.Trinity.World
{
    public partial class QuestTemplate
    {
        public int Id { get; set; }
        public byte QuestType { get; set; }
        public int QuestLevel { get; set; }
        public int MaxScalingLevel { get; set; }
        public int QuestPackageId { get; set; }
        public int MinLevel { get; set; }
        public short QuestSortId { get; set; }
        public short QuestInfoId { get; set; }
        public byte SuggestedGroupNum { get; set; }
        public int RewardNextQuest { get; set; }
        public int RewardXpdifficulty { get; set; }
        public float RewardXpmultiplier { get; set; }
        public int RewardMoney { get; set; }
        public int RewardMoneyDifficulty { get; set; }
        public float RewardMoneyMultiplier { get; set; }
        public int RewardBonusMoney { get; set; }
        public int RewardDisplaySpell1 { get; set; }
        public int RewardDisplaySpell2 { get; set; }
        public int RewardDisplaySpell3 { get; set; }
        public int RewardSpell { get; set; }
        public int RewardHonor { get; set; }
        public int RewardKillHonor { get; set; }
        public int StartItem { get; set; }
        public int RewardArtifactXpdifficulty { get; set; }
        public float RewardArtifactXpmultiplier { get; set; }
        public int RewardArtifactCategoryId { get; set; }
        public int Flags { get; set; }
        public int FlagsEx { get; set; }
        public int RewardItem1 { get; set; }
        public int RewardAmount1 { get; set; }
        public int RewardItem2 { get; set; }
        public int RewardAmount2 { get; set; }
        public int RewardItem3 { get; set; }
        public int RewardAmount3 { get; set; }
        public int RewardItem4 { get; set; }
        public int RewardAmount4 { get; set; }
        public int ItemDrop1 { get; set; }
        public int ItemDropQuantity1 { get; set; }
        public int ItemDrop2 { get; set; }
        public int ItemDropQuantity2 { get; set; }
        public int ItemDrop3 { get; set; }
        public int ItemDropQuantity3 { get; set; }
        public int ItemDrop4 { get; set; }
        public int ItemDropQuantity4 { get; set; }
        public int RewardChoiceItemId1 { get; set; }
        public int RewardChoiceItemQuantity1 { get; set; }
        public int RewardChoiceItemDisplayId1 { get; set; }
        public int RewardChoiceItemId2 { get; set; }
        public int RewardChoiceItemQuantity2 { get; set; }
        public int RewardChoiceItemDisplayId2 { get; set; }
        public int RewardChoiceItemId3 { get; set; }
        public int RewardChoiceItemQuantity3 { get; set; }
        public int RewardChoiceItemDisplayId3 { get; set; }
        public int RewardChoiceItemId4 { get; set; }
        public int RewardChoiceItemQuantity4 { get; set; }
        public int RewardChoiceItemDisplayId4 { get; set; }
        public int RewardChoiceItemId5 { get; set; }
        public int RewardChoiceItemQuantity5 { get; set; }
        public int RewardChoiceItemDisplayId5 { get; set; }
        public int RewardChoiceItemId6 { get; set; }
        public int RewardChoiceItemQuantity6 { get; set; }
        public int RewardChoiceItemDisplayId6 { get; set; }
        public int Poicontinent { get; set; }
        public float Poix { get; set; }
        public float Poiy { get; set; }
        public int Poipriority { get; set; }
        public int RewardTitle { get; set; }
        public int RewardArenaPoints { get; set; }
        public int RewardSkillLineId { get; set; }
        public int RewardNumSkillUps { get; set; }
        public int PortraitGiver { get; set; }
        public int PortraitTurnIn { get; set; }
        public int RewardFactionId1 { get; set; }
        public int RewardFactionValue1 { get; set; }
        public int RewardFactionOverride1 { get; set; }
        public int RewardFactionCapIn1 { get; set; }
        public int RewardFactionId2 { get; set; }
        public int RewardFactionValue2 { get; set; }
        public int RewardFactionOverride2 { get; set; }
        public int RewardFactionCapIn2 { get; set; }
        public int RewardFactionId3 { get; set; }
        public int RewardFactionValue3 { get; set; }
        public int RewardFactionOverride3 { get; set; }
        public int RewardFactionCapIn3 { get; set; }
        public int RewardFactionId4 { get; set; }
        public int RewardFactionValue4 { get; set; }
        public int RewardFactionOverride4 { get; set; }
        public int RewardFactionCapIn4 { get; set; }
        public int RewardFactionId5 { get; set; }
        public int RewardFactionValue5 { get; set; }
        public int RewardFactionOverride5 { get; set; }
        public int RewardFactionCapIn5 { get; set; }
        public int RewardFactionFlags { get; set; }
        public int RewardCurrencyId1 { get; set; }
        public int RewardCurrencyQty1 { get; set; }
        public int RewardCurrencyId2 { get; set; }
        public int RewardCurrencyQty2 { get; set; }
        public int RewardCurrencyId3 { get; set; }
        public int RewardCurrencyQty3 { get; set; }
        public int RewardCurrencyId4 { get; set; }
        public int RewardCurrencyQty4 { get; set; }
        public int AcceptedSoundKitId { get; set; }
        public int CompleteSoundKitId { get; set; }
        public int AreaGroupId { get; set; }
        public int TimeAllowed { get; set; }
        public long? AllowableRaces { get; set; }
        public int QuestRewardId { get; set; }
        public int Expansion { get; set; }
        public string LogTitle { get; set; }
        public string LogDescription { get; set; }
        public string QuestDescription { get; set; }
        public string AreaDescription { get; set; }
        public string PortraitGiverText { get; set; }
        public string PortraitGiverName { get; set; }
        public string PortraitTurnInText { get; set; }
        public string PortraitTurnInName { get; set; }
        public string QuestCompletionLog { get; set; }
        public short? VerifiedBuild { get; set; }
    }
}
